SELECT CONCAT(NAME,"(",SUBSTRING(OCCUPATION,1,1),")") AS RES FROM OCCUPATIONS ORDER BY NAME;
SELECT CONCAT('There are a total of ',COUNT(*),' ',LOWER(OCCUPATION),'s.') as msg
            from OCCUPATIONS
            GROUP BY OCCUPATION
            ORDER BY COUNT(*)  , LOWER(OCCUPATION);