SELECT W1.ID,W2.AGE ,W1.COINS_NEEDED, W1.POWER
FROM Wands AS W1
JOIN Wands_Property AS W2 ON W1.CODE = W2.CODE
WHERE (W1.POWER,W2.AGE,W1.COINS_NEEDED) IN 
(SELECT 
W.POWER,WP.AGE ,MIN(W.COINS_NEEDED)
FROM Wands AS W
JOIN Wands_Property AS WP ON W.CODE = WP.CODE
WHERE WP.IS_EVIL = 0
GROUP BY W.POWER,WP.AGE)
ORDER BY W1.POWER DESC,
                    W2.AGE DESC;
