WITH NEWTABLES AS (
    SELECT NAME , OCCUPATION , 
    ROW_NUMBER()
    OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS ROW_N
    FROM OCCUPATIONS
)
SELECT
    MAX(CASE WHEN OCCUPATION='Doctor' THEN NAME END),
    MAX(CASE WHEN OCCUPATION='Professor' THEN NAME END),
    MAX(CASE WHEN OCCUPATION='Singer' THEN NAME END),
    MAX(CASE WHEN OCCUPATION='Actor' THEN NAME END)
    FROM NEWTABLES
    GROUP BY ROW_N
    ORDER BY ROW_N